### ISSUE TITLE
Create action so new PRs and issues are posted on Teams channel

### ISSUE THREAD

**Issue by dmonroym** [dotnet/project-system-tools#333]
Need to mimic the behavior of project-system repo here: https://github.com/dotnet/project-system/blob/master/.github/workflows/teams-notifications.yml

**Comment by dmonroym** [comment]
@davidwengier despite creating https://github.com/dotnet/project-system-tools/blob/master/.github/workflows/teams-notifications.yml these issues aren't being posted on Teams. Do you know what else could be going on?

**Comment by davidwengier** [comment]
Honestly, no idea. There is a warning about the webhook-uri property, but the same warning exists on the project system repo. Probably doesn't hurt fixing it just in case, but everything looks fine otherwise. 

I guess I can add more logging to PostAdaptiveCards and maybe that will show us whats going on.

**Comment by dmonroym** [comment]
Closed in #339
