### ISSUE TITLE
Elapsed time is missing when copying the content from the Build Logging window

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/project-system-tools#439]
When copying the output from the Build Logging window, the Elapsed time is missing. Also the formatting is a bit weird:

```
Project	Project	Dimensions	Targets	Type	Start	Elapsed	Status
System.CodeDom	.csproj	Debug|AnyCPU|	build	Build	2022-04-29T11:50:18		Finished
Solution Wide				Roslyn	2022-04-29T11:50:13		Running

```

**Comment by drewnoakes** [comment]
Thanks for the issue, @ViktorHofer. 

> the Elapsed time is missing

Fixed in #441.

> the formatting is a bit weird

The values are separated by tabs (tsv), which comes from `Microsoft.VisualStudio.Shell.TableControl`. The same behaviour exists in the Error List, for example. Any change here should be made on the platform side. Perhaps send them a feedback ticket requesting a "Copy as Markdown table" command on the context menu.

As a workaround, you could search/replace `\t` for some other separator (such as `|` for Markdown tables).
