### ISSUE TITLE
'Open Logs...' errors with "Application not found"

### ISSUE THREAD

**Issue by jnm2** [dotnet/project-system-tools#63]
I install MSBuild Structured Log Viewer via [`choco install msbuild-structured-log-viewer`](https://chocolatey.org/packages/msbuild-structured-log-viewer).

![image](https://user-images.githubusercontent.com/8040367/51807057-f6ce8080-224f-11e9-89c2-be19caf885e9.png)

![image](https://user-images.githubusercontent.com/8040367/51807052-e6b6a100-224f-11e9-96ea-264d4c63c3c4.png)

**Comment by drewnoakes** [comment]
I am confused by that stack trace, given:

https://github.com/dotnet/project-system-tools/blob/3a299f7a9263882e4855106f3e1ec987c34ec4a5/src/ProjectSystemTools/BuildLogging/BuildLoggingToolWindow.cs#L220-L238

Can you test with master?

@panopticoncentral do you know if this code changed since the last release?

**Comment by panopticoncentral** [comment]
Yes, it just changed. Prior to the latest release, you needed to install http://www.msbuildlog.com/ for Open Logs to work.
